### ISSUE TITLE
Build 3258 Online 1.69

### ISSUE THREAD

**Issue by gir489returns** [root-cause/v-decompiled-scripts#12]
A new update released today for the "new" Bottom Dollar Bounties DLC.

**Comment by root-cause** [comment]
soon™ (waiting for https://github.com/alloc8or/gta5-nativedb-data to be updated plus a few other things)

**Comment by gir489returns** [comment]
Did they actually change the native table this time? It's been the same for a while.

**Comment by root-cause** [comment]
> Did they actually change the native table this time? It's been the same for a while.

Nope
